export const EventTypes = {
  // Tasks
  TASK_CREATED: "TASK_CREATED",
  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_FAILED: "TASK_FAILED",

  // Agents
  AGENT_ONLINE: "AGENT_ONLINE",
  AGENT_OFFLINE: "AGENT_OFFLINE",
  AGENT_BUSY: "AGENT_BUSY",
  AGENT_IDLE: "AGENT_IDLE",

  // Squads
  SQUAD_SELECTED: "SQUAD_SELECTED",
  SQUAD_UPDATED: "SQUAD_UPDATED",

  // Blog
  BLOG_CREATED: "BLOG_CREATED",
  BLOG_UPDATED: "BLOG_UPDATED",
  BLOG_PUBLISHED: "BLOG_PUBLISHED",

  // Pinterest
  PIN_CREATED: "PIN_CREATED",
  PIN_PUBLISHED: "PIN_PUBLISHED",

  // CRM
  LEAD_RECEIVED: "LEAD_RECEIVED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  SALE_COMPLETED: "SALE_COMPLETED",

  // Traffic
  META_ANALYZED: "META_ANALYZED",
  GOOGLE_ANALYZED: "GOOGLE_ANALYZED",
  PINTEREST_ANALYZED: "PINTEREST_ANALYZED",

  // Dashboard
  DASHBOARD_REFRESH: "DASHBOARD_REFRESH",
  KPI_UPDATED: "KPI_UPDATED",

  // System
  ERROR_OCCURRED: "ERROR_OCCURRED",
  NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
} as const;

export type EventType =
  (typeof EventTypes)[keyof typeof EventTypes];